version: "2"
services:
  tidb:
    image: pingcap/tidb:latest    
    restart: always
  web:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
         - "8080:8080"
      restart: always